[package]
name = "text-selector-try"
version = "0.1.0"
authors = ["Tim Hütz <tim+github@janke.biz>"]
edition = "2018"

[dependencies]
reqwest = { version = "0.10", features = ["blocking"] }
select = "0.4"